/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      // Paleta "Cyber-Refined Narrative" — 1:1 con DESIGN.md frontmatter.
      colors: {
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#b9ccb2',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#84967e',
        'outline-variant': '#3b4b37',
        'surface-tint': '#00e639',
        primary: '#ebffe2',
        'on-primary': '#003907',
        'primary-container': '#00ff41',
        'on-primary-container': '#007117',
        'inverse-primary': '#006e16',
        secondary: '#c6c6c7',
        'on-secondary': '#2f3131',
        'secondary-container': '#454747',
        'on-secondary-container': '#b4b5b5',
        tertiary: '#fcf8f8',
        'on-tertiary': '#313030',
        'tertiary-container': '#dfdcdb',
        'on-tertiary-container': '#616060',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#72ff70',
        'primary-fixed-dim': '#00e639',
        'on-primary-fixed': '#002203',
        'on-primary-fixed-variant': '#00530e',
        'secondary-fixed': '#e2e2e2',
        'secondary-fixed-dim': '#c6c6c7',
        'on-secondary-fixed': '#1a1c1c',
        'on-secondary-fixed-variant': '#454747',
        'tertiary-fixed': '#e5e2e1',
        'tertiary-fixed-dim': '#c8c6c5',
        'on-tertiary-fixed': '#1c1b1b',
        'on-tertiary-fixed-variant': '#474746',
        background: '#131313',
        'on-background': '#e5e2e1',
        'surface-variant': '#353534',
      },
      fontFamily: {
        display: ['"Space Grotesk"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      // Tamaños tipográficos con lineHeight y letterSpacing — 1:1 con DESIGN.md.
      fontSize: {
        'headline-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'mono-label': ['14px', { lineHeight: '1.5', letterSpacing: '0.1em', fontWeight: '500' }],
        'code-snippet': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      spacing: {
        unit: '8px',
        'container-max': '1200px',
        gutter: '24px',
        'section-gap': '120px',
        'card-padding': '32px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
